# analysis.diversity-correlations

In this analysis, we want to quantify:

- Whether Bacteria diversity is correlated with Virus diversity
- Whether Bacteria diversity is correlated with Plant diversity
- Whether habitat or disturbance play a role in these interactions.

To run this analysis, we will use R `lme4` package instead of our regular Python libraries. We will only use Python to create the dataframes.

In [19]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
from daforfer import DaforferDB
import matplotlib.pyplot as plt
import networkx as nx
plt.rcParams['svg.fonttype'] = 'none'
from yaml import load, Loader
from daforfer import DaforferDB
conf = load(open("conf.yaml"), Loader)
db = DaforferDB(conf['database'])
db.toc()

┌────────────────────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│                name                │                                                                                  description                                                                                   │
│              varchar               │                                                                                    varchar                                                                                     │
├────────────────────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ D_bacteriaHits                     │ This table contains all the MOTUS hits obtained, regardless of their status. It contains the library where the detection took place, taxid, scientific name and the PAB labels │
│ D_PABHits                          │ This table contains all the PAB MOTUS hits. It contains the library where the detection took place, taxid, scientific name and the PAB labels                                  │
│ D_virusHits                        │ This table contains all the virus hits. It contains the library where the detection took place, taxid, scientific name and the virus acronym                                   │
│ D_sites                            │ This table contains key information about each of the libraries, such as their site, habitat and host                                                                          │
│ virus_bacteria_library_codetection │ Each row of this table is a bacteria and virus detected in the same library                                                                                                    │
│ D_coocByType                       │ Number and type of cooccurrences between bacteria/virus                                                                                                                        │
│ D_cooccAll                         │ Significative results (0.05) from cooccurrence analysis, including bacteria-bacteria and virus-virus cooccurrences                                                             │
│ D_cooccBactVirus                   │ Significative results (0.05) from cooccurrence analysis, including only virus-bacteria cooccurrences                                                                           │
│ P_coocNetworkLabels                │ Labels of the coocccurence network figure, with their degree                                                                                                                   │
│ P_coocHeatMap                      │ Cooccurrence matrix, weighting each positive or negative interaction by the log-p-value                                                                                        │
│       ·                            │                                    ·                                                                                                                                           │
│       ·                            │                                    ·                                                                                                                                           │
│       ·                            │                                    ·                                                                                                                                           │
│ D_PABAlphaDiv                      │ Alpha Diversity Chao1 and Species Richness in Plant-Associated Bacteria                                                                                                        │
│ T_ADDisturbance                    │ Mann Whitney U test on species richness and Chao1 diversity index by disturbance level                                                                                         │
│ T_ADhabitat                        │ Kruskal Wallis test on species richness and Chao1 diversity index by habitat                                                                                                   │
│ T_ADHabitatPH                      │ Post-Hoc Mann Whitney U analysis on species richness and Chao1 diversity index by habitat                                                                                      │
│ Alpha_diversity_per_site           │ Alpha diversity per site for virus, plant, host and bacteria at site level                                                                                                     │
│ D_ADAllOrganisms                   │ Alpha diversity per site for virus, plant, host and bacteria at site level                                                                                                     │
│ D_ADAllOrganismsSite               │ Alpha diversity per site for virus, plant, host and bacteria at site level                                                                                                     │
│ D_ADAllOrganismsHab                │ Alpha diversity per site for virus, plant, host and bacteria at habitat level                                                                                                  │
│ Site_level_diversity_regression    │ Binomial GLMs and random mixed effect models, obtained in R, at site level                                                                                                     │
│ Habitat_level_diversity_regression │ Binomial GLMs and random mixed effect models, obtained in R, at habitat level                                                                                                  │
├────────────────────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ 30 rows (20 shown)                                                                                                                                                                                        2 columns │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

## Registering data

As everything was computed elswhere, we only need to save the results into the database.

In [20]:
site_level_regression = pd.read_csv("output/regression.site-level.csv", index_col=0)
db.save_dataframe(
    site_level_regression, 
    "T_ADAllOrganismsSite", 
    description="Binomial GLMs and random mixed effect models, obtained in R, at site level"
)
site_level_regression

Saved T_ADAllOrganismsSite to 2025-10-21

,Model,Estimate,StdError,ZValue,PValue,DFres,LogLik
1,Model 1 - species_richness_vir,0.031309,0.012599,2.485076,0.012952,21,-79.648476
2,Model 2 - species_richness_plant,0.042030,0.012164,3.455289,0.000550,21,-79.040404
3,Model 3 - species_richness_plant,0.029504,0.012076,2.443161,0.014559,20,-77.393367
4,Model 3 - species_richness_vir,0.021401,0.012329,1.735895,0.082582,20,-77.393367
5,Model 4 - species_richness_vir,0.031309,0.012952,2.417356,0.015634,19,-79.648476
6,Model 5 - species_richness_plant,0.042030,0.014388,2.921199,0.003487,19,-79.040404
7,Model 6 - species_richness_plant,0.029504,0.013810,2.136376,0.032649,18,-77.393367
8,Model 6 - species_richness_vir,0.021401,0.011980,1.786395,0.074035,18,-77.393367
9,Model 7 - species_richness_vir,0.031309,0.012952,2.417361,0.015634,19,-79.648476
10,Model 8 - species_richness_plant,0.042030,0.014388,2.921194,0.003487,19,-79.040404
11,Model 9 - species_richness_plant,0.029504,0.013811,2.136347,0.032651,18,-77.393367
12,Model 9 - species_richness_vir,0.021401,0.011980,1.786380,0.074038,18,-77.393367

In [21]:
habitat_level_regression = pd.read_csv("output/regression.habitat-level.csv", index_col=0)
db.save_dataframe(
    habitat_level_regression, 
    "T_ADAllOrganismsHab", 
    description="Binomial GLMs and random mixed effect models, obtained in R, at habitat level"
)
habitat_level_regression

Saved T_ADAllOrganismsHab to 2025-10-21

,Model,Estimate,StdError,ZValue,PValue,DFres,LogLik
1,Model 1 - species_richness_vir,0.011629,0.004193,2.773340,0.005548,2,-15.494493
2,Model 2 - species_richness_plant,0.001213,0.009818,0.123523,0.901693,2,-17.515836
3,Model 3 - species_richness_plant,0.004492,0.005392,0.833136,0.404768,1,-15.153956
4,Model 3 - species_richness_vir,0.012178,0.003816,3.191076,0.001417,1,-15.153956

In [22]:
db.conn.close()