# 2025-06-13. Sprint - data - processing

## Summary 

In this notebook, I'll prepare all the data for later analysis, so I don't need to repeat the data processing across each analysis.
It will also increase the consistency of my data. 

- Data is loaded from the Motus classification files.
- We assign the different taxonomic ranks.
- We merge the data with McLeish2024 metadata, to add Host taxon, Habitat, etc. 
- We save the data into a CSV file
- We merge the data with the Sanchis2021 Plant-Associated Bacteria metadata.
- We save the data into a CSV file

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
habitat_palette = {
    "Crop": "#0CAB7B", 
    "Edge": "#3A8DFA", 
    "Oak": "#FB2231",
    "Wasteland": "#FFC51F"
}
from skbio.diversity.alpha import shannon, chao1
import taxoniq
from scipy.stats import kruskal
from skbio.stats.ordination import pcoa
import tqdm
from scipy.stats import linregress
from skbio import TreeNode

## Load data from Motus

In [2]:
index_df = pd.read_csv("../results/2025-06-09.motus-g1/source.csv", sep=",", header=None, index_col=0, names=['library', 'read1', 'read2'])
index_df

,library,read1,read2
1,PV001,PV1_18807_ATCACG_read1.fastq.gz,PV1_18807_ATCACG_read2.fastq.gz
2,PV002,PV2_18808_TGACCA_read1.fastq.gz,PV2_18808_TGACCA_read2.fastq.gz
3,PV003,PV3_16716_GGCTAC_read1.fastq.gz,PV3_16716_GGCTAC_read2.fastq.gz
4,PV003bgi,FCH5VT5ALXX_L5_HKRDPLAgshTAACRAAPEI-203_1.fq.zip,FCH5VT5ALXX_L5_HKRDPLAgshTAACRAAPEI-203_2.fq.zip
5,PV004bgi,FCH5VT5ALXX_L5_HKRDPLAgshTAADRAAPEI-204_1.fq.zip,FCH5VT5ALXX_L5_HKRDPLAgshTAADRAAPEI-204_2.fq.zip
...,...,...,...
320,PV586,PV586_03661AAB_AGTTGC_read1.fastq.gz,PV586_03661AAB_AGTTGC_read2.fastq.gz
321,PV587,PV587_03662AAB_ACCTTC_read1.fastq.gz,PV587_03662AAB_ACCTTC_read2.fastq.gz
322,PV588,PV588_03663AAB_TCGCAT_read1.fastq.gz,PV588_03663AAB_TCGCAT_read2.fastq.gz
323,PV589,PV589_03664AAB_AGGACT_read1.fastq.gz,PV589_03664AAB_AGGACT_read2.fastq.gz
324,PV590,PV590_03982AAC_TAGCTT_R1_001.fastq.gz,PV590_03982AAC_TAGCTT_R2_001.fastq.

In [3]:
def load_motus_classification(x, library):
    try:
        u = pd.read_csv(x, sep="\t")
    except pd.errors.EmptyDataError:
        u = pd.DataFrame(data=[], columns=['mOTU', 'taxonomy', 'taxid', 'abundance'])
    u.columns = ['mOTU', 'taxonomy', 'taxid', 'abundance']
    u = u.dropna(subset=['taxid'])
    u['library'] = library
    return u

In [4]:
motus_df = pd.concat(
    index_df['library'].apply(
        lambda x: load_motus_classification(f"../results/2025-06-09.motus-g1/{x}.classification.csv", x)
    ).to_list()
)
motus_df['abundance'] = motus_df['abundance'].astype(float)
motus_df['log10_abundance'] = motus_df['abundance'].apply(np.log10)
motus_df

/tmp/ipykernel_1241046/61898022.py:1: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  motus_df = pd.concat(

,mOTU,taxonomy,taxid,abundance,library,log10_abundance
0,ref_mOTU_v31_06099,Mycoplasma genitalium,2097.0,1.0,PV001,0.000000
0,ref_mOTU_v31_03148,uncultured Clostridium sp.,59620.0,9.0,PV002,0.954243
1,ref_mOTU_v31_06099,Mycoplasma genitalium,2097.0,1.0,PV002,0.000000
2,ref_mOTU_v31_06426,Candidatus Phytoplasma solani,69896.0,6.0,PV002,0.778151
1,ref_mOTU_v31_01500,Neisseria sp. oral taxon 014,641148.0,3.0,PV003,0.477121
...,...,...,...,...,...,...
7,ref_mOTU_v31_10306,Paenibacillus sp. TI45-13ar,1886670.0,1.0,PV587,0.000000
0,ref_mOTU_v31_03148,uncultured Clostridium sp.,59620.0,9.0,PV588,0.954243
1,ref_mOTU_v31_05265,Rothia mucilaginosa [Rothia sp. HMSC071B01/Rot...,43675.0,1.0,PV588,0.000000
0,ref_mOTU_v31_01746,Exiguobacterium sibiricum,332410.0,1.0,PV589,0.000000
1,ref_mOTU_v31_03148,uncultured Clostridium sp.,59620.0,1.0,PV589,0.000000

## Taxonomy ranks

In [5]:
def fault_tolerant_rank(x):
    try:
        return taxoniq.Taxon(x).rank.name
    except KeyError:
        return pd.NA
    
def obtain_taxonomic_level(x, rank_name):
    try:
        return [level.scientific_name for level in taxoniq.Taxon(x).ranked_lineage if level.rank.name == rank_name][0]
    except IndexError:
        return pd.NA
motus_df['taxid'] = motus_df['taxid'].astype(int)
motus_df['rank'] = motus_df.taxid.apply(fault_tolerant_rank)
motus_df = motus_df.dropna(subset=['rank']).copy()
motus_df['phylum'] = motus_df['taxid'].apply(lambda x: obtain_taxonomic_level(x, 'phylum'))
motus_df['class'] = motus_df['taxid'].apply(lambda x: obtain_taxonomic_level(x, 'class'))
motus_df['family'] = motus_df['taxid'].apply(lambda x: obtain_taxonomic_level(x, 'family'))
motus_df['order'] = motus_df['taxid'].apply(lambda x: obtain_taxonomic_level(x, 'order'))
motus_df['genus'] = motus_df['taxid'].apply(lambda x: obtain_taxonomic_level(x, 'genus'))
motus_df['species'] = motus_df['taxid'].apply(lambda x: taxoniq.Taxon(x).scientific_name)
motus_df

,mOTU,taxonomy,taxid,abundance,library,log10_abundance,rank,phylum,class,family,order,genus,species
0,ref_mOTU_v31_06099,Mycoplasma genitalium,2097,1.0,PV001,0.000000,species,Mycoplasmatota,<NA>,Mycoplasmoidaceae,Mycoplasmoidales,Mycoplasmoides,Mycoplasmoides genitalium
0,ref_mOTU_v31_03148,uncultured Clostridium sp.,59620,9.0,PV002,0.954243,species,Bacillota,Clostridia,Clostridiaceae,Eubacteriales,Clostridium,uncultured Clostridium sp.
1,ref_mOTU_v31_06099,Mycoplasma genitalium,2097,1.0,PV002,0.000000,species,Mycoplasmatota,<NA>,Mycoplasmoidaceae,Mycoplasmoidales,Mycoplasmoides,Mycoplasmoides genitalium
2,ref_mOTU_v31_06426,Candidatus Phytoplasma solani,69896,6.0,PV002,0.778151,species,Mycoplasmatota,Mollicutes,Acholeplasmataceae,Acholeplasmatales,Candidatus Phytoplasma,Candidatus Phytoplasma solani
1,ref_mOTU_v31_01500,Neisseria sp. oral taxon 014,641148,3.0,PV003,0.477121,species,Pseudomonadota,Betaproteobacteria,Neisseriaceae,Neisseriales,Neisseria,Neisseria sp. oral taxon 014
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5,ref_mOTU_v31_01209,Pseudomonas syringae,317,1.0,PV587,0.000000,species,Pseudomonadota,Gammaproteobacteria,Pseudomonadaceae,Pseudomonadales,Pseudomonas,Pseudomonas syringae
7,ref_mOTU_v31_10306,Paenibacillus sp. TI45-13ar,1886670,1.0,PV587,0.000000,species,Bacillota,Bacilli,Paenibacillaceae,Bacillales,Paenibacillus,Paenibacillus nuruki
0,ref_mOTU_v31_03148,uncultured Clostridium sp.,59620,9.0,PV588,0.954243,species,Bacillota,Clostridia,Clostridiaceae,Eubacteriales,Clostridium,uncultured Clostridium sp.
1,ref_mOTU_v31_05265,Rothia mucilaginosa [Rothia sp. HMSC071B01/Rot...,43675,1.0,PV588,0.000000,species,Actinomycetota,Actinomycetes,Micrococcaceae,Micrococcales,Rothia,Rothia mucilaginosa
1,ref_mOTU_v31_03148,uncultured Clostridium sp.,59620,1.0,PV589,0.000000,species,Bacillota,Clostridia,Clostridiaceae,Eubacteriales,Clostridium,uncultured Clostridium sp.

## Metadata merge (McLeish2024)

In [6]:
mc24_table1 = pd.read_csv("../data/mcleish2024/nph20054-sup-0002-TablesS1.csv", sep=';')
mc24_table2 = pd.read_csv("../data/mcleish2024/nph20054-sup-0002-TablesS2.csv", sep=';')
mc24_table2 = mc24_table2.dropna(subset=['Library_code'])
mc24_table2['Collection_code'] = mc24_table2['Collection_code'].apply(lambda x: x.split("_")[0])
sample_reference = pd.merge(mc24_table1, mc24_table2, on='Collection_code').groupby(['Site_code', 'Collection_code', 'Library_code', 'Location', 'Host_taxon', 'Habitat', 'No_extracts', 'Longitude','Latitude'], as_index=False)['Date'].apply(lambda x: len(list(x)))
sample_reference

,Site_code,Collection_code,Library_code,Location,Host_taxon,Habitat,No_extracts,Longitude,Latitude,Date
0,C1,C1F,PV534,Aranjuez,Diplotaxis erucoides,Crop,3,-3.593308,40.051302,1
1,C1,C1F,PV535,Aranjuez,Brassica oleracea,Crop,17,-3.593308,40.051302,1
2,C1,C1F,PV538,Aranjuez,Brassica oleracea,Crop,8,-3.593308,40.051302,1
3,C1,C1F,PV540,Aranjuez,Picris echioides,Crop,1,-3.593308,40.051302,1
4,C1,C1F,PV544,Aranjuez,Sisymbrium runcinatum,Crop,4,-3.593308,40.051302,1
...,...,...,...,...,...,...,...,...,...,...
318,Z1,Z1V,PV590,Villaconejos,Zea mays,Crop,11,-3.476076,40.050052,1
319,Z2,Z2V,PV047,Villamanrique de Tajo,Zea mays,Crop,13,-3.131000,40.044720,1
320,Z2,Z2V,PV048,Villamanrique de Tajo,Desconocida 4,Crop,9,-3.131000,40.044720,1
321,Z2,Z2V,PV527,Villamanrique de Tajo,Convolvulus arvensis,Crop,4,-3.131000,40.044720,1
322,Z2,Z2V,PV529,Villamanrique de Tajo,Picris echioides,Crop,1,-3.131000,40.044720,1

In [7]:
motus_df = pd.merge(motus_df, sample_reference, left_on='library', right_on='Library_code')

## Genome accession

Important to enable phylogentic-aware diversity calculations. We need to map each taxon-id to a genome accession present in the GTDB phylogenetic tree.

In [9]:
tree = TreeNode.read("../data/taxonomy/bac120.tree")
tree_tip_names = list(tree.subset())
tree_tip_names

['GB GCA 913047795.1',
 'GB GCA 023356515.1',
 'GB GCA 021803845.1',
 'GB GCA 902776365.1',
 'GB GCA 022775595.1',
 'RS GCF 000442275.2',
 'RS GCF 030813355.1',
 'GB GCA 001468865.1',
 'GB GCA 011525685.1',
 'GB GCA 031285105.1',
 'GB GCA 017433825.1',
 'RS GCF 900106765.1',
 'RS GCF 013839445.1',
 'GB GCA 018716805.1',
 'RS GCF 026625125.1',
 'GB GCA 003542575.1',
 'GB GCA 003280985.1',
 'GB GCA 903789595.1',
 'GB GCA 902782995.1',
 'GB GCA 021806885.1',
 'GB GCA 023436395.1',
 'GB GCA 021296435.1',
 'GB GCA 015060255.1',
 'RS GCF 001552415.1',
 'GB GCA 017524445.1',
 'RS GCF 001875665.1',
 'RS GCF 016908275.1',
 'RS GCF 947487805.1',
 'RS GCF 005871165.1',
 'GB GCA 913757435.1',
 'GB GCA 017619905.1',
 'RS GCF 017940385.1',
 'GB GCA 012839605.1',
 'RS GCF 003024235.1',
 'GB GCA 023266455.1',
 'GB GCA 017617725.1',
 'GB GCA 002425405.1',
 'GB GCA 018829775.1',
 'GB GCA 018623785.1',
 'GB GCA 013824325.1',
 'GB GCA 025054615.1',
 'GB GCA 900314345.1',
 'GB GCA 020627705.1',
 'GB GCA 022843855.1',
 'GB GCA 900321965.1',
 'GB GCA 023383055.1',
 'RS GCF 001942335.1',
 'GB GCA 026706445.1',
 'GB GCA 023954015.1',
 'GB GCA 937863215.1',
 'GB GCA 017391185.1',
 'GB GCA 902591415.1',
 'GB GCA 009783195.1',
 'GB GCA 015067975.1',
 'GB GCA 028714495.1',
 'GB GCA 003511125.1',
 'RS GCF 900130045.1',
 'GB GCA 001464275.1',
 'GB GCA 024229195.1',
 'GB GCA 947175015.1',
 'GB GCA 944363745.1',
 'GB GCA 021817915.1',
 'GB GCA 002440845.1',
 'GB GCA 902805645.1',
 'RS GCF 027105055.1',
 'GB GCA 904420235.1',
 'GB GCA 027487815.1',
 'RS GCF 002157465.1',
 'GB GCA 030746455.1',
 'GB GCA 012518435.1',
 'GB GCA 028872975.1',
 'GB GCA 030530765.1',
 'GB GCA 002367285.1',
 'GB GCA 030838885.1',
 'GB GCA 002313335.1',
 'GB GCA 018818925.1',
 'RS GCF 020535565.1',
 'GB GCA 900762515.1',
 'GB GCA 002686995.1',
 'GB GCA 029212405.1',
 'GB GCA 945952245.1',
 'GB GCA 018825985.1',
 'GB GCA 001312505.1',
 'GB GCA 947584805.1',
 'RS GCF 009363755.1',
 'GB GCA 020637675.1',
 'RS GCF 000174435.1',
 'GB GCA 945919075.1',
 'GB GCA 945863965.1',
 'RS GCF 009930815.1',
 'GB GCA 028277205.1',
 'GB GCA 903861115.1',
 'GB GCA 017476765.1',
 'GB GCA 929200485.1',
 'GB GCA 902826575.1',
 'RS GCF 000615445.1',
 'GB GCA 009778605.1',
 'GB GCA 020629035.1',
 'GB GCA 002413345.1',
 'GB GCA 021775515.1',
 'GB GCA 016931115.1',
 'GB GCA 918241715.1',
 'GB GCA 934746185.1',
 'GB GCA 002784465.1',
 'GB GCA 017450645.1',
 'GB GCA 902568465.1',
 'GB GCA 002423905.1',
 'GB GCA 027618475.1',
 'GB GCA 916438445.1',
 'GB GCA 003518055.1',
 'GB GCA 017555925.1',
 'GB GCA 016124415.1',
 'GB GCA 021297975.1',
 'GB GCA 016293645.1',
 'GB GCA 017525455.1',
 'RS GCF 017312365.1',
 'GB GCA 944389975.1',
 'RS GCF 018362775.1',
 'GB GCA 001508155.1',
 'GB GCA 017474125.1',
 'GB GCA 946530775.1',
 'GB GCA 020446425.1',
 'GB GCA 913775795.1',
 'GB GCA 031287505.1',
 'GB GCA 009377605.1',
 'GB GCA 020201365.1',
 'GB GCA 003280295.1',
 'RS GCF 002096815.1',
 'GB GCA 937864175.1',
 'RS GCF 001988955.1',
 'GB GCA 007375655.1',
 'GB GCA 903868455.1',
 'GB GCA 024278285.1',
 'RS GCF 003602275.1',
 'GB GCA 030445265.1',
 'GB GCA 902799555.1',
 'RS GCF 017875235.1',
 'RS GCF 000519125.1',
 'GB GCA 029960045.1',
 'RS GCF 002407245.1',
 'GB GCA 002403155.1',
 'GB GCA 947446585.1',
 'GB GCA 018831055.1',
 'GB GCA 005768755.1',
 'RS GCF 022664465.1',
 'GB GCA 016213105.1',
 'GB GCA 937965735.1',
 'GB GCA 002721675.1',
 'GB GCA 002068775.1',
 'RS GCF 022811605.1',
 'GB GCA 900768875.1',
 'GB GCA 902623415.1',
 'GB GCA 021734365.1',
 'GB GCA 020634135.1',
 'GB GCA 902787275.1',
 'GB GCA 024405155.1',
 'GB GCA 947167745.1',
 'RS GCF 016746085.1',
 'GB GCA 024638765.1',
 'RS GCF 000008485.1',
 'GB GCA 030427555.1',
 'RS GCF 009695875.1',
 'GB GCA 030532245.1',
 'GB GCA 023396465.1',
 'GB GCA 014238425.1',
 'GB GCA 001801175.1',
 'RS GCF 001655685.1',
 'GB GCA 001003205.1',
 'GB GCA 017472925.1',
 'GB GCA 025774735.1',
 'GB GCA 902806325.1',
 'RS GCF 005938125.1',
 'GB GCA 015067945.1',
 'GB GCA 026389955.1',
 'GB GCA 024654415.1',
 'GB GCA 020722095.1',
 'GB GCA 945890755.1',
 'RS GCF 003319115.1',
 'RS GCF 001813295.1',
 'RS GCF 001997385.1',
 'GB GCA 015061685.1',
 'GB GCA 020722965.1',
 'GB GCA 900755065.1',
 'RS GCF 022712095.1',
 'GB GCA 902464345.1',
 'RS GCF 031180975.1',
 'GB GCA 000720535.1',
 'GB GCA 022561955.1',
 'GB GCA 029624765.1',
 'RS GCF 023278185.1',
 'GB GCA 017480455.1',
 'GB GCA 003650285.1',
 'GB GCA 900767415.1',
 'GB GCA 017398105.1',
 'RS GCF 000425645.1',
 'RS GCF 900177545.1',
 'GB GCA 947460255.1',
 'GB GCA 902525995.1',
 'GB GCA 017439845.1',
 'GB GCA 902792515.1',
 'GB GCA 029263555.1',
 'RS GCF 003860215.1',
 'GB GCA 002295635.1',
 'GB GCA 021324435.1',
 'GB GCA 009787445.1',
 'RS GCF 000169255.2',
 'RS GCF 014651915.1',
 'RS GCF 012396605.1',
 'RS GCF 020880415.1',
 'RS GCF 008831235.1',
 'GB GCA 028292315.1',
 'GB GCA 903934285.1',
 'GB GCA 028712225.1',
 'GB GCA 937958985.1',
 'GB GCA 947631395.1',
 'GB GCA 943349045.1',
 'GB GCA 910585205.1',
 'RS GCF 001422445.1',
 'GB GCA 000153385.1',
 'GB GCA 017560605.1',
 'GB GCA 015068655.1',
 'GB GCA 028696455.1',
 'GB GCA 019638085.1',
 'GB GCA 000998425.1',
 'GB GCA 003456765.1',
 'GB GCA 021787535.1',
 'GB GCA 029982245.1',
 'GB GCA 029557905.1',
 'RS GCF 001468225.1',
 'GB GCA 022616555.1',
 'GB GCA 027494035.1',
 'GB GCA 900450455.1',
 'GB GCA 017511685.1',
 'GB GCA 902613805.1',
 'RS GCF 001908185.1',
 'GB GCA 031282605.1',
 'GB GCA 017942035.1',
 'GB GCA 937975855.1',
 'GB GCA 021780275.1',
 'GB GCA 009784355.1',
 'GB GCA 009779525.1',
 'GB GCA 016204945.1',
 'GB GCA 026391675.1',
 'GB GCA 022614915.1',
 'GB GCA 027010905.1',
 'RS GCF 017874215.1',
 'GB GCA 007133145.1',
 'RS GCF 001721045.1',
 'GB GCA 030408505.1',
 'GB GCA 002011745.1',
 'GB GCA 946480705.1',
 'RS GCF 900631945.1',
 'GB GCA 019749915.1',
 'GB GCA 015488495.1',
 'GB GCA 019116865.1',
 'GB GCA 017381015.1',
 'GB GCA 024710825.1',
 'RS GCF 003344965.1',
 'RS GCF 916618895.1',
 'RS GCF 900176335.1',
 'GB GCA 013152955.1',
 'RS GCF 004153545.1',
 'GB GCA 030040655.1',
 'RS GCF 014652415.1',
 'RS GCF 900240305.1',
 'GB GCA 017468435.1',
 'GB GCA 026392115.1',
 'GB GCA 028819945.1',
 'GB GCA 948466945.1',
 'RS GCF 000716675.1',
 'GB GCA 029267315.1',
 'GB GCA 021298355.1',
 'GB GCA 947589635.1',
 'RS GCF 008041935.1',
 'RS GCF 014803385.1',
 'GB GCA 900582625.1',
 'RS GCF 005144415.1',
 'GB GCA 013141415.1',
 'GB GCA 902462295.1',
 'GB GCA 902497065.1',
 'GB GCA 023474975.1',
 'GB GCA 002335175.1',
 'GB GCA 910577805.1',
 'GB GCA 900547685.1',
 'GB GCA 001800095.1',
 'GB GCA 023244815.1',
 'GB GCA 029884165.1',
 'GB GCA 945872375.1',
 'GB GCA 003132145.1',
 'RS GCF 014635685.1',
 'GB GCA 945870105.1',
 'RS GCF 900604935.1',
 'GB GCA 020845735.1',
 'GB GCA 900767645.1',
 'RS GCF 017876315.1',
 'RS GCF 000504085.1',
 'RS GCF 017311165.1',
 'GB GCA 030746535.1',
 'GB GCA 905182265.1',
 'GB GCA 021790475.1',
 'GB GCA 020404485.1',
 'RS GCF 015752315.1',
 'RS GCF 014194695.1',
 'GB GCA 005786885.1',
 'RS GCF 008312935.1',
 'GB GCA 900319565.1',
 'GB GCA 030538425.1',
 'GB GCA 017450435.1',
 'RS GCF 030540945.1',
 'GB GCA 903944345.1',
 'GB GCA 949296295.1',
 'RS GCF 022414575.1',
 'GB GCA 947039485.1',
 'RS GCF 009735585.1',
 'GB GCA 023257325.1',
 'GB GCA 025462785.1',
 'GB GCA 945877965.1',
 'RS GCF 001995215.1',
 'GB GCA 017624495.1',
 'RS GCF 002563895.1',
 'GB GCA 031272375.1',
 'GB GCA 030950765.1',
 'GB GCA 028717885.1',
 'GB GCA 018714105.1',
 'GB GCA 009924725.1',
 'GB GCA 017553165.1',
 'GB GCA 010028775.1',
 'GB GCA 002329335.1',
 'GB GCA 902611845.1',
 'RS GCF 000403455.2',
 'RS GCF 946998255.1',
 'GB GCA 937997955.1',
 'GB GCA 937872775.1',
 'GB GCA 902471845.1',
 'RS GCF 014207135.1',
 'RS GCF 001434895.1',
 'GB GCA 026987255.1',
 'GB GCA 903959175.1',
 'GB GCA 013215905.1',
 'GB GCA 001796965.1',
 'RS GCF 016756495.1',
 'GB GCA 900760575.1',
 'GB GCA 017405675.1',
 'GB GCA 020438595.1',
 'GB GCA 022565395.1',
 'GB GCA 947305005.1',
 'GB GCA 030705805.1',
 'RS GCF 000332315.1',
 'RS GCF 014217625.1',
 'RS GCF 013167955.1',
 'RS GCF 002205635.1',
 'GB GCA 027023175.1',
 'GB GCA 026129185.1',
 'GB GCA 900761085.1',
 'GB GCA 002171155.1',
 'GB GCA 021162265.1',
 'GB GCA 016179865.1',
 'RS GCF 017795745.1',
 'RS GCF 002056295.1',
 'RS GCF 000341065.1',
 'GB GCA 002453265.1',
 'GB GCA 902526865.1',
 'RS GCF 902705545.1',
 'GB GCA 913057215.1',
 'GB GCA 937900285.1',
 'RS GCF 003263785.1',
 'GB GCA 934772525.1',
 'GB GCA 002292855.1',
 'GB GCA 900542275.1',
 'GB GCA 002840275.1',
 'GB GCA 018005585.1',
 'RS GCF 001938945.1',
 'GB GCA 016282095.1',
 'GB GCA 002490725.1',
 'RS GCF 000498355.1',
 'RS GCF 026241755.1',
 'GB GCA 903970525.1',
 'GB GCA 020403425.1',
 'GB GCA 017404985.1',
 'RS GCF 001457595.1',
 'RS GCF 014655955.1',
 'RS GCF 023721795.1',
 'GB GCA 003669615.1',
 'RS GCF 015840915.1',
 'GB GCA 934668515.1',
 'GB GCA 902566945.1',
 'GB GCA 031265025.1',
 'RS GCF 003967555.1',
 'GB GCA 016870945.1',
 'RS GCF 030866785.1',
 'RS GCF 028290435.1',
 'GB GCA 947631925.1',
 'GB GCA 012521465.1',
 'GB GCA 017411305.1',
 'GB GCA 910574865.1',
 'RS GCF 026122815.1',
 'RS GCF 024347295.1',
 'GB GCA 944391015.1',
 'GB GCA 934122275.1',
 'GB GCA 949290895.1',
 'GB GCA 947450005.1',
 'GB GCA 024642005.1',
 'GB GCA 017503865.1',
 'GB GCA 902788995.1',
 'GB GCA 016187945.1',
 'RS GCF 901873365.1',
 'GB GCA 019116115.1',
 'RS GCF 029690045.1',
 'RS GCF 004339245.1',
 'GB GCA 016763645.1',
 'GB GCA 022571985.1',
 'GB GCA 947173755.1',
 'GB GCA 902522585.1',
 'RS GCF 003454795.1',
 'GB GCA 017405595.1',
 'RS GCF 000245735.1',
 'RS GCF 900143625.1',
 'GB GCA 001458075.1',
 'RS GCF 018919485.1',
 'RS GCF 004000925.1',
 'GB GCA 022566895.1',
 'GB GCA 025464795.1',
 'GB GCA 900318605.1',
 'GB GCA 902826055.1',
 'RS GCF 900177625.1',
 'RS GCF 018390515.1',
 'GB GCA 944393315.1',
 'GB GCA 958417225.1',
 'GB GCA 018667335.1',
 'RS GCF 001514535.1',
 'GB GCA 902463725.1',
 'RS GCF 014698475.1',
 'GB GCA 020635255.1',
 'GB GCA 001464995.1',
 'GB GCA 017530735.1',
 'GB GCA 900759845.1',
 'RS GCF 900129635.1',
 'RS GCF 013215705.1',
 'RS GCF 017355525.1',
 'GB GCA 017507105.1',
 'GB GCA 948436025.1',
 'GB GCA 003142075.1',
 'GB GCA 001778905.1',
 'RS GCF 006491645.1',
 'RS GCF 001832905.1',
 'RS GCF 000835165.1',
 'GB GCA 023228925.1',
 'GB GCA 020627605.1',
 'GB GCA 027035985.1',
 'RS GCF 022014595.1',
 'GB GCA 021733665.1',
 'GB GCA 023266075.1',
 'GB GCA 944324875.1',
 'GB GCA 902537425.1',
 'GB GCA 024276255.1',
 'RS GCF 001277215.2',
 'GB GCA 024403615.1',
 'GB GCA 029959615.1',
 'GB GCA 014381465.1',
 'GB GCA 008638005.1',
 'GB GCA 947454545.1',
 'RS GCF 024197615.1',
 'GB GCA 002772575.1',
 'RS GCF 001896545.1',
 'GB GCA 020853095.1',
 'GB GCA 002869435.1',
 'GB GCA 002729695.1',
 'GB GCA 003162335.1',
 'GB GCA 016882485.1',
 'RS GCF 003060895.1',
 'GB GCA 005881275.1',
 'GB GCA 018663505.1',
 'RS GCF 000210895.1',
 'GB GCA 946405485.1',
 'GB GCA 946547025.1',
 'GB GCA 001778985.1',
 'RS GCF 005222485.1',
 'GB GCA 002696685.1',
 'GB GCA 027451505.1',
 'GB GCA 021780075.1',
 'RS GCF 003173775.1',
 'RS GCF 014596475.1',
 'GB GCA 001778785.1',
 'GB GCA 001788095.1',
 'GB GCA 022446945.1',
 'GB GCA 015055525.1',
 'GB GCA 013140935.1',
 'RS GCF 007859195.1',
 'GB GCA 001804205.1',
 'GB GCA 944386295.1',
 'RS GCF 002563955.1',
 'GB GCA 024280755.1',
 'GB GCA 000436475.1',
 'RS GCF 000153725.1',
 'GB GCA 947260025.1',
 'GB GCA 945487445.1',
 'GB GCA 945897865.1',
 'RS GCF 905120465.1',
 'GB GCA 003551005.1',
 'GB GCA 937893885.1',
 'GB GCA 029245065.1',
 'RS GCF 001717465.1',
 'GB GCA 028819495.1',
 'RS GCF 030538655.1',
 'GB GCA 030653355.1',
 'RS GCF 030699305.1',
 'GB GCA 947303375.1',
 'GB GCA 018056145.1',
 'GB GCA 903831805.1',
 'GB GCA 014377845.1',
 'GB GCA 946408995.1',
 'GB GCA 947453545.1',
 'GB GCA 003216975.1',
 'RS GCF 024621935.1',
 'RS GCF 000092985.1',
 'GB GCA 009785885.1',
 'RS GCF 012034335.1',
 'GB GCA 947304025.1',
 'GB GCA 025997275.1',
 'RS GCF 000012385.1',
 'RS GCF 024460775.1',
 'GB GCA 028696185.1',
 'GB GCA 001769535.1',
 'GB GCA 947568765.1',
 'GB GCA 020523885.1',
 'GB GCA 029004355.1',
 'GB GCA 002011415.1',
 'GB GCA 002705125.1',
 'GB GCA 905196265.1',
 'GB GCA 903902895.1',
 'GB GCA 947588835.1',
 'GB GCA 017860635.1',
 'RS GCF 001274945.1',
 'GB GCA 029938715.1',
 'GB GCA 016234985.1',
 'GB GCA 023430245.1',
 'GB GCA 934408585.1',
 'GB GCA 021205095.1',
 'GB GCA 020057535.1',
 'GB GCA 024400995.1',
 'RS GCF 018070345.1',
 'GB GCA 902826615.1',
 'GB GCA 014859655.1',
 'GB GCA 944384585.1',
 'GB GCA 022779305.1',
 'GB GCA 012517935.1',
 'RS GCF 030012525.1',
 'GB GCA 002069525.1',
 'RS GCF 023555495.1',
 'GB GCA 913043205.1',
 'GB GCA 902565895.1',
 'GB GCA 026417495.1',
 'GB GCA 017307315.1',
 'RS GCF 008795955.1',
 'GB GCA 009296315.1',
 'RS GCF 009863025.1',
 'GB GCA 002167605.1',
 'RS GCF 000518165.1',
 'GB GCA 947496065.1',
 'GB GCA 024400955.1',
 'RS GCF 001708405.1',
 'GB GCA 009700485.1',
 'RS GCF 002368115.1',
 'RS GCF 012641395.1',
 'RS GCF 012563145.1',
 'GB GCA 003208885.1',
 'GB GCA 903892365.1',
 'GB GCA 002454975.1',
 'GB GCA 003223635.1',
 'GB GCA 020060845.1',
 'RS GCF 001482405.1',
 'GB GCA 937949555.1',
 'GB GCA 902596185.1',
 'RS GCF 005862235.1',
 'GB GCA 025459425.1',
 'GB GCA 028715705.1',
 'GB GCA 013393545.1',
 'GB GCA 029289235.1',
 'GB GCA 945868195.1',
 'RS GCF 029351045.1',
 'GB GCA 017425765.1',
 'GB GCA 947631375.1',
 'GB GCA 021300395.1',
 'RS GCF 022829585.1',
 'GB GCA 015060865.1',
 'RS GCF 000826685.1',
 'RS GCF 000430545.1',
 'GB GCA 902519375.1',
 'GB GCA 030532025.1',
 'GB GCA 017984495.1',
 'GB GCA 945900015.1',
 'GB GCA 026000155.1',
 'RS GCF 024105655.1',
 'GB GCA 001704275.1',
 'GB GCA 029100605.1',
 'GB GCA 009840695.1',
 'GB GCA 002320455.1',
 'GB GCA 021801825.1',
 'RS GCF 025490915.1',
 'RS GCF 947367125.1',
 'GB GCA 023248175.1',
 'GB GCA 016927865.1',
 'GB GCA 947598585.1',
 'RS GCF 025755255.1',
 'GB GCA 001796525.1',
 'RS GCF 001273855.1',
 'RS GCF 009846755.1',
 'GB GCA 010671905.1',
 'GB GCA 020060235.1',
 'GB GCA 949282835.1',
 'GB GCA 903871555.1',
 'RS GCF 002216065.1',
 'GB GCA 021824565.1',
 'GB GCA 024233785.1',
 'RS GCF 003333315.1',
 'GB GCA 017527865.1',
 'GB GCA 944323075.1',
 'GB GCA 030065825.1',
 'GB GCA 020635675.1',
 'GB GCA 902782505.1',
 'GB GCA 018969385.1',
 'GB GCA 903910795.1',
 'RS GCF 014196535.1',
 'RS GCF 001421355.1',
 'GB GCA 001818695.1',
 'GB GCA 015490875.1',
 'GB GCA 016722565.1',
 'GB GCA 002862405.1',
 'GB GCA 945883615.1',
 'RS GCF 014251755.1',
 'RS GCF 902809835.1',
 'RS GCF 000410535.2',
 'RS GCF 900636515.1',
 'RS GCF 008271345.1',
 'GB GCA 902519835.1',
 'GB GCA 903829325.1',
 'GB GCA 023139045.1',
 'RS GCF 900115195.1',
 'GB GCA 028687425.1',
 'GB GCA 018712145.1',
 'GB GCA 947632515.1',
 'GB GCA 947461495.1',
 'RS GCF 001293645.1',
 'GB GCA 017516745.1',
 'RS GCF 025947285.1',
 'GB GCA 001412425.1',
 'RS GCF 025263565.1',
 'GB GCA 900772495.1',
 'GB GCA 029974225.1',
 'RS GCF 030519355.1',
 'GB GCA 017627255.1',
 'RS GCF 014280235.1',
 'RS GCF 947496195.1',
 'GB GCA 030041375.1',
 'GB GCA 938045325.1',
 'RS GCF 000478825.2',
 'GB GCA 937949945.1',
 'RS GCF 024756275.1',
 'RS GCF 001613245.1',
 'GB GCA 014803985.1',
 'GB GCA 017380515.1',
 'GB GCA 002238885.1',
 'RS GCF 020179755.1',
 'RS GCF 001612745.1',
 'GB GCA 903824505.1',
 'GB GCA 018241125.1',
 'RS GCF 012926525.1',
 'GB GCA 002477505.1',
 'GB GCA 958367245.1',
 'RS GCF 001427665.1',
 'GB GCA 944325655.1',
 'GB GCA 017436135.1',
 'GB GCA 900759475.1',
 'GB GCA 945876115.1',
 'GB GCA 021299715.1',
 'GB GCA 003554945.1',
 'GB GCA 902540595.1',
 'GB GCA 905235525.1',
 'GB GCA 028707675.1',
 'GB GCA 027490415.1',
 'RS GCF 004123295.1',
 'GB GCA 002257235.1',
 'GB GCA 027315105.1',
 'RS GCF 003851725.1',
 'GB GCA 030680295.1',
 'GB GCA 947165805.1',
 'RS GCF 900110695.1',
 'RS GCF 002362255.1',
 'GB GCA 030741175.1',
 'RS GCF 029222905.1',
 'RS GCF 001431315.2',
 'GB GCA 012838225.1',
 'RS GCF 001294535.1',
 'RS GCF 022844445.1',
 'RS GCF 001750145.1',
 'RS GCF 029504395.1',
 'GB GCA 937890835.1',
 'GB GCA 951812505.1',
 'RS GCF 014287955.1',
 'GB GCA 015067245.1',
 'GB GCA 017507855.1',
 'GB GCA 019419895.1',
 'GB GCA 934168305.1',
 'GB GCA 020628495.1',
 'GB GCA 031257215.1',
 'RS GCF 000758705.1',
 'GB GCA 001821135.1',
 'RS GCF 002154895.1',
 'GB GCA 017462445.1',
 'GB GCA 905215425.1',
 'GB GCA 025355325.1',
 'GB GCA 021805735.1',
 'GB GCA 023411225.1',
 'RS GCF 022427965.1',
 'RS GCF 030499535.1',
 'RS GCF 003207795.1',
 'GB GCA 012515635.1',
 'GB GCA 003218525.1',
 'RS GCF 013408745.1',
 'RS GCF 900101965.1',
 'GB GCA 905214375.1',
 'GB GCA 900318995.1',
 'GB GCA 030153935.1',
 'RS GCF 017566145.1',
 'GB GCA 018064365.1',
 'GB GCA 937958685.1',
 'RS GCF 013425765.1',
 'RS GCF 019203185.1',
 'RS GCF 016820635.1',
 'GB GCA 001778545.1',
 'RS GCF 000012225.1',
 'GB GCA 009784625.1',
 'GB GCA 945869715.1',
 'GB GCA 018646605.1',
 'GB GCA 016699935.1',
 'GB GCA 031263585.1',
 'RS GCF 900114355.1',
 'RS GCF 027988105.1',
 'RS GCF 008039565.1',
 'GB GCA 030679035.1',
 'RS GCF 001238275.1',
 'RS GCF 001439925.1',
 'RS GCF 900637165.1',
 'GB GCA 946886365.1',
 'RS GCF 000377905.1',
 'GB GCA 015903945.1',
 'GB GCA 016188005.1',
 'GB GCA 001751015.1',
 'RS GCF 003627055.1',
 'RS GCF 014773395.1',
 'GB GCA 944349765.1',
 'GB GCA 946403215.1',
 'RS GCF 000021305.1',
 'GB GCA 017617435.1',
 'GB GCA 024426085.1',
 'RS GCF 018688495.1',
 'GB GCA 020847985.1',
 'GB GCA 028702495.1',
 'RS GCF 022024035.1',
 'RS GCF 014898075.1',
 'GB GCA 949284695.1',
 'GB GCA 016937135.1',
 'GB GCA 009694365.1',
 'RS GCF 000373925.1',
 'GB GCA 018334675.1',
 'RS GCF 025398275.1',
 'GB GCA 017471245.1',
 'RS GCF 025421775.1',
 'RS GCF 002807685.1',
 'RS GCF 004346205.1',
 'GB GCA 903828645.1',
 'GB GCA 947168935.1',
 'GB GCA 905207705.1',
 'GB GCA 022710245.1',
 'GB GCA 902492105.1',
 'GB GCA 017557635.1',
 'RS GCF 002157355.1',
 'GB GCA 937982565.1',
 'RS GCF 000364165.2',
 'GB GCA 002337045.1',
 'RS GCF 027924905.1',
 'GB GCA 945860385.1',
 'GB GCA 017400965.1',
 'GB GCA 029237755.1',
 'RS GCF 001690275.1',
 'GB GCA 018665815.1',
 'GB GCA 016869415.1',
 'GB GCA 025924495.1',
 'RS GCF 000712595.1',
 'GB GCA 001512885.1',
 'RS GCF 000280495.2',
 'GB GCA 023423855.1',
 'GB GCA 031260565.1',
 'RS GCF 003932785.1',
 'GB GCA 023264755.1',
 'RS GCF 008831085.1',
 'GB GCA 020719165.1',
 'RS GCF 023333595.1',
 'RS GCF 001723295.1',
 'GB GCA 949296305.1',
 'RS GCF 002865545.1',
 'GB GCA 007135115.1',
 'GB GCA 903882765.1',
 'GB GCA 003537755.1',
 'GB GCA 016778465.1',
 'GB GCA 017516065.1',
 'GB GCA 934097105.1',
 'GB GCA 902796305.1',
 'RS GCF 905120355.1',
 'GB GCA 002419135.1',
 'GB GCA 944387115.1',
 'GB GCA 030039755.1',
 'GB GCA 030532125.1',
 'GB GCA 016866635.1',
 'GB GCA 020025075.1',
 'GB GCA 013287775.1',
 'GB GCA 013695775.1',
 'RS GCF 002812085.1',
 'GB GCA 018830415.1',
 'GB GCA 017467805.1',
 'GB GCA 023254845.1',
 'GB GCA 029219425.1',
 'RS GCF 001704295.1',
 'GB GCA 900316105.1',
 'GB GCA 023898525.1',
 'GB GCA 003233075.1',
 'GB GCA 948468275.1',
 'RS GCF 000695095.2',
 'GB GCA 013152545.1',
 'GB GCA 946623205.1',
 'GB GCA 947475465.1',
 'GB GCA 026707935.1',
 'GB GCA 016743235.1',
 'GB GCA 012514895.1',
 'GB GCA 016880375.1',
 'GB GCA 003535775.1',
 'GB GCA 011524395.1',
 'GB GCA 021778515.1',
 'GB GCA 028404615.1',
 'RS GCF 026988655.1',
 'GB GCA 944321525.1',
 'RS GCF 014280965.1',
 'GB GCA 009993585.1',
 'GB GCA 021849595.1',
 'RS GCF 028206995.1',
 'RS GCF 030412915.1',
 'GB GCA 017938145.1',
 'GB GCA 903868795.1',
 'GB GCA 029247845.1',
 'GB GCA 002839435.1',
 'GB GCA 016180815.1',
 'GB GCA 016210435.1',
 'GB GCA 017504205.1',
 'GB GCA 947245665.1',
 'GB GCA 027025255.1',
 'RS GCF 006088815.1',
 'GB GCA 947456955.1',
 'RS GCF 002237535.1',
 'RS GCF 029202525.1',
 'GB GCA 017439805.1',
 'GB GCA 913061365.1',
 'GB GCA 017624645.1',
 'RS GCF 020883535.1',
 'GB GCA 945865925.1',
 'GB GCA 022841915.1',
 'GB GCA 949286465.1',
 'GB GCA 029054535.1',
 'GB GCA 937877545.1',
 'RS GCF 001645385.1',

In [10]:
gtdb_metadata = pd.read_csv("../data/taxonomy/bac120_metadata.tsv", sep="\t")

In [11]:
gtdb_metadata[gtdb_metadata['gtdb_genome_representative'].apply(lambda x: x.replace("_", " ")).isin(tree_tip_names)]

,accession,ambiguous_bases,checkm2_completeness,checkm2_contamination,checkm2_model,checkm_completeness,checkm_contamination,checkm_marker_count,checkm_marker_lineage,checkm_marker_set_count,...,ssu_silva_blast_align_len,ssu_silva_blast_bitscore,ssu_silva_blast_evalue,ssu_silva_blast_perc_identity,ssu_silva_blast_subject_id,ssu_silva_taxonomy,total_gap_length,trna_aa_count,trna_count,trna_selenocysteine_count
0,RS_GCF_000657795.2,0,100.00,0.14,Specific,99.53,0.00,426,o__Burkholderiales (UID4000),213,...,1528,2822,0,100,JHEP02000033.784.2325,Bacteria;Proteobacteria;Gammaproteobacteria;Bu...,0,19,55,1
1,RS_GCF_001072555.1,7,100.00,0.52,Specific,99.81,0.09,773,g__Staphylococcus (UID294),178,...,896,1655,0,100,CP030246.976624.978176,Bacteria;Firmicutes;Bacilli;Staphylococcales;S...,700,14,36,0
2,RS_GCF_003050715.1,0,100.00,0.04,Specific,99.60,0.22,769,g__Burkholderia (UID4006),248,...,1530,2826,0,100,CP012193.2238151.2239686,Bacteria;Proteobacteria;Gammaproteobacteria;Bu...,585,19,52,0
3,RS_GCF_016772635.1,0,100.00,0.16,Specific,100.00,0.04,1169,f__Enterobacteriaceae (UID5139),340,...,1538,2841,0,100,CP032396.2469808.2471361,Bacteria;Proteobacteria;Gammaproteobacteria;En...,0,19,86,1
4,GB_GCA_000615405.1,0,100.00,1.37,Specific,99.62,0.57,471,o__Lactobacillales (UID543),264,...,1545,2854,0,100,CP020604.1893382.1894929,Bacteria;Firmicutes;Bacilli;Lactobacillales;St...,0,17,45,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
584377,GB_GCA_949039885.1,0,98.92,0.35,General,98.79,3.22,420,f__Lachnospiraceae (UID1286),207,...,none,none,none,none,none,none,200,16,31,0
584378,GB_GCA_905234525.1,14,98.73,1.30,General,90.12,1.09,420,f__Lachnospiraceae (UID1286),207,...,none,none,none,none,none,none,1001,18,35,0
584379,GB_GCA_948663365.1,8,76.65,0.14,Specific,76.98,0.38,406,o__Bacteroidales (UID2617),265,...,none,none,none,none,none,none,184,17,26,0
584380,GB_GCA_948940555.1,0,99.99,0.11,Specific,97.55,0.13,406,o__Bacteroidales (UID2617),265,...,none,none,none,none,none,none,109,18,42,0
584381,GB_GCA_000753355.2,24,100.00,1.66,Specific,99.17,0.78,332,o__Clostridiales (UID1375),124,...,1491,2754,0,100,CCNN01000005.2986.4476,Bacteria;Firmicutes;Clostridia;Clostridiales;C...,11212,19,124,1

In [12]:
gtdb_accessions = gtdb_metadata[['ncbi_taxid', 'gtdb_genome_representative']].drop_duplicates('ncbi_taxid', keep='first').copy()
gtdb_accessions['gtdb_genome_representative'] = gtdb_accessions['gtdb_genome_representative'].apply(lambda x: x.replace("_", " "))
gtdb_accessions

        ncbi_taxid gtdb_genome_representative
0          1331258         RS GCF 000657795.2
1             1282         RS GCF 006742205.1
2          2135698         RS GCF 000172415.1
3            90371         RS GCF 000006945.2
4          1236944         RS GCF 029023865.1
...            ...                        ...
584333     1752224         GB GCA 001464955.1
584341     2665509         RS GCF 000006945.2
584345     2530375         RS GCF 004348725.1
584349     2169409         RS GCF 003097655.1
584366     2589941         RS GCF 006442975.2

[89701 rows x 2 columns]

In [13]:

motus_df = pd.merge(motus_df, gtdb_accessions, how='left', left_on='taxid', right_on='ncbi_taxid')

## Save data

In [14]:
motus_df.columns

Index(['mOTU', 'taxonomy', 'taxid', 'abundance', 'library', 'log10_abundance',
       'rank', 'phylum', 'class', 'family', 'order', 'genus', 'species',
       'Site_code', 'Collection_code', 'Library_code', 'Location',
       'Host_taxon', 'Habitat', 'No_extracts', 'Longitude', 'Latitude', 'Date',
       'ncbi_taxid', 'gtdb_genome_representative'],
      dtype='object')

In [20]:
motus_df[[
    'taxonomy', 'taxid', 'gtdb_genome_representative', 'abundance', 'library', 'Site_code', 'Collection_code', 'Location', 'Longitude', 'Latitude', 'Host_taxon', 'Habitat', 'No_extracts', 'phylum', 'class', 'family',
    'order', 'genus', 'species'
]].to_csv("../results/2025-06-13.sprint/base.motus-hits.csv", sep=";", index=None)

## Merge with PAB database

In [21]:
sanchis21 = pd.read_csv("../data/sanchis21/sanchis21.tableS1.csv", sep='\t').drop_duplicates(subset='TaxId')
# taxid = sanchis21['taxid'].to_list()
sanchis21['pab_type'] = sanchis21.apply(lambda x: 'pathogen' if x['PAB-phyto'] == 'P' else pd.NA, axis=1)
sanchis21['pab_type'] = sanchis21.apply(lambda x: 'symbiont' if x['PAB-symb'] == 'S' else x['pab_type'], axis=1)
sanchis21['pab_type'] = sanchis21['pab_type'].fillna('unknown')

In [22]:
pab_motus_df = pd.merge(motus_df, sanchis21[['TaxId', 'pab_type']], left_on='taxid', right_on='TaxId', how='inner')

## Save data

In [23]:
pab_motus_df[[
    'taxonomy', 'taxid', 'gtdb_genome_representative', 'abundance', 'library', 'Site_code', 'Collection_code', 'Location', 'Longitude', 'Latitude',  'Host_taxon', 'Habitat', 'No_extracts', 'phylum', 'class', 'family',
    'order', 'genus', 'species', 'pab_type'
]].to_csv("../results/2025-06-13.sprint/base.motus-hits-pab.csv", sep=";", index=None)