# Q&A notebook

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.pyplot as plt
plt.rcParams['svg.fonttype'] = 'none'
from yaml import load, Loader
from daforfer import DaforferDB
conf = load(open("conf.yaml"), Loader)
db = DaforferDB(conf['database'])
db.toc()

┌──────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│         name         │                                                                                  description                                                                                   │
│       varchar        │                                                                                    varchar                                                                                     │
├──────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ D_sites              │ This table contains key information about each of the libraries, such as their site, habitat and host                                                                          │
│ D_bacteriaHits       │ This table contains all the MOTUS hits obtained, regardless of their status. It contains the library where the detection took place, taxid, scientific name and the PAB labels │
│ D_PABHits            │ This table contains all the PAB MOTUS hits. It contains the library where the detection took place, taxid, scientific name and the PAB labels                                  │
│ d_TableS1            │ Table S1: Library sites and context                                                                                                                                            │
│ D_PABOTUs            │ This table summarizes most of the information of our detected OTUs, including host_range, site_range, habitat_range, etc.                                                      │
│ D_virusHits          │ This table contains all the virus hits. It contains the library where the detection took place, taxid, scientific name and the virus acronym                                   │
│ D_coocDetections     │ Library code and number of cooccurring pairs detected                                                                                                                          │
│ D_coocPairDetections │ Number of cooccurring pairs per library. Deduplication can help assessing how many detections took place at library level                                                      │
│ D_Site_level_div     │ Site-level diversity and number of cooccurring virus-bacteria                                                                                                                  │
│ D_Habitat_level_div  │ Habitat-level diversity and number of cooccurring virus-bacteria                                                                                                               │
│        ·             │                       ·                                                                                                                                                        │
│        ·             │                       ·                                                                                                                                                        │
│        ·             │                       ·                                                                                                                                                        │
│ viral_rank_plot      │ All virus OTUs ordered by their number of hits                                                                                                                                 │
│ D_VirusOTUs          │ This table summarizes most of the information of previously detected virus OTUs, including host_range, site_range, habitat_range, etc.                                         │
│ D_virusBactCodetect  │ Each row of this table is a bacteria and virus detected in the same library                                                                                                    │
│ D_coocByType         │ Number and type of cooccurrences between bacteria/virus                                                                                                                        │
│ D_cooccAll           │ Significative results (0.05) from cooccurrence analysis, including bacteria-bacteria and virus-virus cooccurrences                                                             │
│ D_cooccBactVirus     │ Significative results (0.05) from cooccurrence analysis, including only virus-bacteria cooccurrences                                                                           │
│ P_coocNetworkLabels  │ Labels of the coocccurence network figure, with their degree                                                                                                                   │
│ P_coocHeatMap        │ Cooccurrence matrix, weighting each positive or negative interaction by the log-p-value                                                                                        │
│ T_coocBipStats       │ Cooccurrence network connectance, Modularity and Nestedness (NODF) analyzed using null model r2d-derived Z-scores and t-test 1 sample                                          │
│ T_honBipStats        │ Host organism network bipartite analysis results                                                                                                                               │
├──────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ 36 rows (20 shown)                                                                                                                                                                          2 columns │
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

## How many virus detections were reported in McLeish2024?

In [2]:

len(db.conn.sql('SELECT * FROM D_virusHits').df()) # 1616 hits in our database q000016

1616

## How many taxa?

In [3]:
len(db.conn.sql('SELECT * FROM D_virusHits').df()['scientific_name'].unique()) # 158 hits in our database q000017

158

## Did all the PAB bacteria detected correspond to at least a virus in their library?

In [4]:
virus = db.conn.sql('SELECT * FROM D_virusHits').df()
bacteria = db.conn.sql('SELECT * FROM D_pabHits').df()
virus_positive_libraries = virus['library'].unique()
bacteria['is_in_virus'] = bacteria['library'].isin(virus_positive_libraries)
bacteria.groupby(['scientific_name'], as_index=False)['is_in_virus'].sum().query('is_in_virus != 0')

                scientific_name  is_in_virus
0    Achromobacter xylosoxidans            2
1        Acidovorax sp. Leaf160            1
2         Acidovorax sp. Leaf78            1
3       Acinetobacter baumannii            1
4          Acinetobacter pittii            3
..                          ...          ...
122      Stutzerimonas stutzeri            1
123        Variovorax paradoxus            2
124      Xanthomonas campestris            6
125  Xaviernesmea rhizosphaerae            1
126      Xylophilus sp. Leaf220            3

[124 rows x 2 columns]

In [5]:
len(bacteria.taxid.unique())

127

## Were all the virus detected in the pressence of a bacteria?

In [6]:
virus = db.conn.sql('SELECT * FROM D_virusHits').df()
bacteria = db.conn.sql('SELECT * FROM D_pabHits').df()
bacteria_positive_libraries = bacteria['library'].unique()
virus['is_in_bacteria'] = virus['library'].isin(bacteria_positive_libraries)
virus.groupby(['scientific_name'], as_index=False)['is_in_bacteria'].sum().query('is_in_bacteria != 0')

                        scientific_name  is_in_bacteria
0      African eggplant yellowing virus               2
1           Ageratum latent virus RNA 1               1
2                  Alfalfa enamovirus 1               1
3            Alfalfa mosaic virus RNA 2               3
4    Arabidopsis halleri partitivirus 1               1
..                                  ...             ...
147             Watermelon mosaic virus              26
153               Yam bean mosaic virus               2
154                    Yam mosaic virus               4
156                 Youcai mosaic virus              17
157        Zucchini yellow mosaic virus               2

[109 rows x 2 columns]

## How many libraries has the site with most libraries?

In [7]:
pd.read_csv('output/metadata.site-library.csv', sep=';').value_counts('site')

site
L1    40
L3    35
L2    35
Q2    25
Q1    24
L4    23
E2    21
E4    19
Q3    16
E3    15
E1    14
Q4    13
M1     8
Z1     6
C2     6
C1     5
M3     5
H3     5
M4     4
M2     4
H2     4
H1     4
Z2     4
Name: count, dtype: int64

## What's the virus with wider range?

In [8]:
m = pd.merge(
    pd.read_csv("output/hits.virus.csv", sep=';'),
    pd.read_csv('output/metadata.site-library.csv', sep=';'),
    on='library'
)[['acronym', 'taxid', 'host_taxon']].drop_duplicates().value_counts('acronym').reset_index()

In [9]:
m

    acronym  count
0      CMV3     83
1     TMGMV     65
2     PZSV3     58
3       TMV     52
4     RuCMV     50
..      ...    ...
153    SbDV      1
154  CymRSV      1
155    CaMV      1
156    PCV2      1
157    AEV1      1

[158 rows x 2 columns]

In [10]:
m.query('count == 1')

        acronym  count
95         TYMV      1
96        BPeMV      1
97        BYSMV      1
98     BYDV_GPV      1
99   BYDV_KerII      1
..          ...    ...
153        SbDV      1
154      CymRSV      1
155        CaMV      1
156        PCV2      1
157        AEV1      1

[63 rows x 2 columns]

In [11]:
m = pd.merge(
    pd.read_csv("output/hits.bacteria.csv", sep=';').query('is_pab == True'),
    pd.read_csv('output/metadata.site-library.csv', sep=';'),
    on='library'
)[['scientific_name', 'taxid', 'host_taxon']].drop_duplicates().value_counts('scientific_name').reset_index()

In [12]:
len(m.query('count == 1'))

55

In [13]:
db.conn.close()